name: Deploy Vite site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read version
        id: version
        run: |
          VERSION=$(grep -oP '(?<=VERSION = ")[0-9.]+' src/version.ts)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version detected: $VERSION"

      - name: Check if version already deployed
        id: check
        run: |
          # If gh-pages exists, check version.txt
          if git ls-remote --exit-code origin gh-pages &> /dev/null; then
            if git show origin/gh-pages:version.txt | grep -q "$VERSION"; then
              echo "This version ($VERSION) is already deployed. Skipping deploy."
              exit 0
            fi
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project for GitHub Pages
        run: npx vite build --base="/${{ github.event.repository.name }}/"

      - name: Save version marker
        run: echo "$VERSION" > dist/version.txt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
